name: Remove Closed Issues from Triage Board

on:
  issues:
    types: [closed]

jobs:
  removeCard:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Triage Test Board
          column: Done
          action: delete
          repo-token: ${{ secrets.GITHUB_TOKEN }}
